inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'node_modules/**/*'
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*'

Naming/VariableNumber:
  Enabled: false
