inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  Exclude:
    - "bin/*"
    - "node_modules/**/*"
    - "db/schema.rb"
  NewCops: enable
  TargetRubyVersion: 3.3.7

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - "db/migrate/*"

Metrics/MethodLength:
  Exclude:
    - "db/migrate/*"

Layout/LineLength:
  Max: 130

Metrics/BlockLength:
  Max: 30
  Exclude:
    - "spec/**/*"
    - "config/routes.rb"
    - "db/schema.rb"
Naming/VariableNumber:
  Enabled: false

Layout/InitialIndentation:
  Exclude:
    - "app/views/**/*.slim"

Style/FrozenStringLiteralComment:
  Exclude:
    - "app/views/**/*.slim"

Layout/TrailingEmptyLines:
  Exclude:
    - "app/views/**/*.slim"

Rails/I18nLocaleTexts:
  Enabled: false

Rails/FilePath:
  Exclude:
    - "spec/rails_helper.rb"

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 15

RSpec/NestedGroups:
  Max: 5

Rails/ThreeStateBooleanColumn:
  Exclude:
    - "db/schema.rb"
