version: '3.3'
services:
  postgres:
    container_name: math_trainer
    image: postgres:10.10-alpine
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    environment:
      POSTGRES_USER: ${USER}
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
