version: '3.3'
services:
  postgres:
    image: postgres:14
    container_name: postgres_math_trainer
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: "trust"
  redis:
    image: redis:7
    ports:
      - '127.0.0.1:6379:6379'
    container_name: redis_math_trainer
