# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/additions', type: :request do
  # Addition. As you add validations to Addition, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Addition.create! valid_attributes
      get additions_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      addition = Addition.create! valid_attributes
      get addition_url(addition)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_addition_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      addition = Addition.create! valid_attributes
      get edit_addition_url(addition)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Addition' do
        expect do
          post additions_url, params: { addition: valid_attributes }
        end.to change(Addition, :count).by(1)
      end

      it 'redirects to the created addition' do
        post additions_url, params: { addition: valid_attributes }
        expect(response).to redirect_to(addition_url(Addition.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Addition' do
        expect do
          post additions_url, params: { addition: invalid_attributes }
        end.to change(Addition, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post additions_url, params: { addition: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested addition' do
        addition = Addition.create! valid_attributes
        patch addition_url(addition), params: { addition: new_attributes }
        addition.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the addition' do
        addition = Addition.create! valid_attributes
        patch addition_url(addition), params: { addition: new_attributes }
        addition.reload
        expect(response).to redirect_to(addition_url(addition))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        addition = Addition.create! valid_attributes
        patch addition_url(addition), params: { addition: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested addition' do
      addition = Addition.create! valid_attributes
      expect do
        delete addition_url(addition)
      end.to change(Addition, :count).by(-1)
    end

    it 'redirects to the additions list' do
      addition = Addition.create! valid_attributes
      delete addition_url(addition)
      expect(response).to redirect_to(additions_url)
    end
  end
end
