# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/multiplications', type: :request do
  # Multiplication. As you add validations to Multiplication, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Multiplication.create! valid_attributes
      get multiplications_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      multiplication = Multiplication.create! valid_attributes
      get multiplication_url(multiplication)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_multiplication_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      multiplication = Multiplication.create! valid_attributes
      get edit_multiplication_url(multiplication)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Multiplication' do
        expect do
          post multiplications_url, params: { multiplication: valid_attributes }
        end.to change(Multiplication, :count).by(1)
      end

      it 'redirects to the created multiplication' do
        post multiplications_url, params: { multiplication: valid_attributes }
        expect(response).to redirect_to(multiplication_url(Multiplication.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Multiplication' do
        expect do
          post multiplications_url, params: { multiplication: invalid_attributes }
        end.to change(Multiplication, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post multiplications_url, params: { multiplication: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested multiplication' do
        multiplication = Multiplication.create! valid_attributes
        patch multiplication_url(multiplication), params: { multiplication: new_attributes }
        multiplication.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the multiplication' do
        multiplication = Multiplication.create! valid_attributes
        patch multiplication_url(multiplication), params: { multiplication: new_attributes }
        multiplication.reload
        expect(response).to redirect_to(multiplication_url(multiplication))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        multiplication = Multiplication.create! valid_attributes
        patch multiplication_url(multiplication), params: { multiplication: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested multiplication' do
      multiplication = Multiplication.create! valid_attributes
      expect do
        delete multiplication_url(multiplication)
      end.to change(Multiplication, :count).by(-1)
    end

    it 'redirects to the multiplications list' do
      multiplication = Multiplication.create! valid_attributes
      delete multiplication_url(multiplication)
      expect(response).to redirect_to(multiplications_url)
    end
  end
end
