default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  port: <%= ENV.fetch('POSTGRES_PORT', 5432) %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>

development:
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  port: <%= ENV.fetch('POSTGRES_PORT', 5432) %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  database: math_trainer_development

test:
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  port: <%= ENV.fetch('POSTGRES_PORT', 5432) %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  database: math_trainer_test

