default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  port: <%= ENV.fetch('POSTGRES_PORT', 5432) %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  username: postgres
  password: postgres

development:
  <<: *default
  database: math_trainer_development

test:
  <<: *default
  database: math_trainer_test

production:
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
